### ISSUE TITLE
Access to view the billing template

### ISSUE THREAD

**Issue by garvsd** [GoogleCloudPlatform/logging-analytics-samples#13]
Hi Xiangshen, please if you can extend access to the billing [template](https://lookerstudio.google.com/reporting/e426208d-e31e-4910-ba30-c8425957568f/page/BLaAD/preview) for Looker dashboard you have setup in your observability samples repository. Thank you.

**Comment by xiangshen-dk** [comment]
Update the access for the template. Thanks for letting us know.
