### ISSUE TITLE
Reference to connection struct in VPC flow logs needs to be lowercase

### ISSUE THREAD

**Issue by przemyslawsroka** [GoogleCloudPlatform/logging-analytics-samples#2]
connection struct needs to be referenced using lowercase. With capital letters "CONNECTION" the query can be executed, but returns no information about destination IP.

Replace:
SELECT JSON_VALUE(json_payload.CONNECTION.dest_ip) AS dest_ip,

With:
SELECT JSON_VALUE(json_payload.connection.dest_ip) AS dest_ip,

https://github.com/GoogleCloudPlatform/logging-analytics-samples/blob/2ab8db778bef98abfb5d631aabaf014cbeeb6c62/samples/kubernetes/network_top_ips_for_clusters.sql#L21

**Comment by charlesbaer** [comment]
Thanks! Submitted PR to address.
